//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StadisticJCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_Ciudadanos
    {
        public int idCiudadano { get; set; }
        public int idProvincia { get; set; }
        public int idProfesion { get; set; }
        public int idEstatus { get; set; }
        public string sexo { get; set; }
        public string cedula { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fechaNac { get; set; }
        public string calle { get; set; }
        public decimal numero { get; set; }
        public string sector { get; set; }
        public byte[] foto { get; set; }
    
        public virtual TBM_Estatus TBM_Estatus { get; set; }
        public virtual TBM_Provincia TBM_Provincia { get; set; }
        public virtual TBM_Profesion TBM_Profesion { get; set; }
    }
}
